fixes some linking issues

diff --git a/v2/buildDocsForProduction b/v2/buildDocsForProduction
--- a/v2/buildDocsForProduction
+++ b/v2/buildDocsForProduction
@@ -7,6 +7,12 @@ GREEN='\033[32m'
 
 MODE=production npx docusaurus build
 
+if [[ $? -ne 0 ]]
+then
+    echo "build failed... exiting!"
+    exit 1
+fi
+
 # remove unnecessary files
 rm ./build/sitemap.xml
 rm ./build/index.html
