adds process env flags to control how code checking works

diff --git a/v2/buildDocsForProduction b/v2/buildDocsForProduction
--- a/v2/buildDocsForProduction
+++ b/v2/buildDocsForProduction
@@ -9,12 +9,17 @@ ignore_error="$1"
 
 # Clear docusaurus cache before building
 npx docusaurus clear .
-MODE=production npx docusaurus build
 
-if [[ $? -ne 0 ]] && [[ $ignore_error != "true" ]]
+if [[ $ignore_error != "true" ]]
 then
-    echo "build failed... exiting!"
-    exit 1
+    MODE=production npx docusaurus build
+    if [[ $? -ne 0 ]]
+    then
+        echo "build failed... exiting!"
+        exit 1
+    fi
+else
+    MODE=production CODE_TYPE_CHECK=nothing npx docusaurus build
 fi
 
 echo "Copying to supertokens-backend-website..."
